weights: runs/train/yolov5s_results_batch_sz64/weights/best.pt
cfg: models/RPS_yolov5s.yaml
data: /Volumes/USB/CodingProjects/New_Rock_Paper_Scissors/ObjectDetection/Augmented_Data/data.yaml
hyp: data/hyps/hyp.scratch-low.yaml
epochs: 50
batch_size: 64
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: ram
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: runs/train
name: yolov5s_results_batch_sz64_augmented4
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs/train/yolov5s_results_batch_sz64_augmented4
